name: Executar Scan de Segurança

on:
  workflow_dispatch:
    inputs:
      senha_desafio:
        description: 'Digite a senha secreta (Vulnerabilidade Física das Fotos)'
        required: true
        default: ''

jobs:
  jogar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4.1.7

      - name: Configurar o Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.12'

      - name: Rodar o Jogo Interativo
        run: python jogo.py "${{ github.event.inputs.senha_desafio }}"
